### ISSUE TITLE
Use XML instead of CSV

### ISSUE THREAD

**Issue by jindrichmynarz** [os-data/eu-budget-2014#1]
As mentioned in os-data/registry#36 the CSV format of the dataset is a simplified subset of its XML version. Thus, it would be better to use XML directly to avoid loss of data.

**Comment by danfowler** [comment]
Hi @jindrichmynarz the [native format](http://fiscal.dataprotocols.org/spec/#form-and-structure) for the fiscal data package is CSV, and the initial work by @HimmelStein was an attempt to map the original XML into CSV as faithfully as possible.  That is, we're not using the original simplified CSV.  I do think there's still work to do on mapping the original XML, though.

**Comment by HimmelStein** [comment]
agree. @jindrichmynarz, it would be great that someone would transform the XML to RDF, then later, we can analyze what kind of information is missing in the CSV files, or what kind of information in XML files are difficult to be captured by FDP, or even how to extend FDP.

**Comment by jindrichmynarz** [comment]
@danfowler, I'm not suggesting to package XML, but to use XML as the source.

**Comment by danfowler** [comment]
@jindrichmynarz OK. But it does seem to me that the XML files are being used as the source: https://github.com/os-data/eu-budget-2014/tree/master/data

**Comment by jindrichmynarz** [comment]
OK, then I misunderstood what @HimmelStein told me. Sorry for the confusion. I'm closing the issue.
